# Example docker-compose file to get all required services running for an SPT server and dedicated client
#
# Change the volume mounts to point to the right paths, of course
services:
  # SPT Server container
  spt_server:
    # See https://github.com/zhliau/fika-spt-server-docker
    # This is my own SPT server image, but you can choose to use any other working SPT docker image
    image: ghcr.io/zhliau/fika-spt-server-docker:latest
    container_name: spt_server
    volumes:
      # I like to mount my server files from the host into the container so I can easily add/change mods
      - /host/path/to/serverfiles:/opt/server
    ports:
      - 6969:6969
    # Mark the container as healthy once the server has started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/launcher/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
 
  # Dedicated client container
  fika_dedi:
    image: ghcr.io/zhliau/fika-headless-docker:latest
    container_name: fika_dedi
    volumes:
      # Set this to the path on the host to the FIKA client files
      - /host/path/to/fika:/opt/tarkov
    environment:
      - PROFILE_ID=adadadadadadaadadadad
      # Use service name from above, docker-compose resolves this to the SPT server container
      - SERVER_URL=spt_server
      - SERVER_PORT=6969
    # Wait to start the dedicated client until the server is healthy
    depends_on:
      spt_server:
        condition: service_healthy
    ports:
      - 25565:25565/udp

  # Restarter service, to restart the dedicated client at 11 UTC every day
  # Replace "fika_dedi" with the name of your dedicated client container
  restarter:
    image: docker:cli
    container_name: fika_restarter
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        echo "Scheduling restart - container start $$(date +'%Y%m%d %H:%M')"
        while true; do
        if [ "$$(date +'%H:%M')" = '11:00' ]; then
        echo "Restarting dedicated container on $$(date +'%H:%M')"
        docker restart fika_dedi
        fi
        sleep 60
        done
